=== Mémo de référence pour les commandes à envoyer

==== Candle

0x0014: Effects
---------------------
Value: [saturation][color][mode][00][speed][00]

Parameter  | Value
------------- | -------------
saturation | 00-> ff, ff => low, 00 => high
color | color as RGB hex
mode  | 01 = Fade, 02 = Jump RBG, 03 = Fade RGB, 04 = Candle Effect
speed | 00-> ff, 00 => really slow, 01 => really fast, 02 => slower

#####Candle effect
`saturation + color = ff000000`


0x0016: Get / Set Color
---------------------
Value  | Result
------------- | -------------
00000000 | led off
ff000000 | candle color
00+hex  | hex color

#####Example
00ff0000 => full red

==== Candle v6

0x0017: Effects
---------------------
Value: [saturation][color][mode][00][speed][00]

Parameter  | Value
------------- | -------------
saturation | 00-> ff, ff => low, 00 => high
color | color as RGB hex
mode  | 00 = Flash, 01 = Pulse, 02 = Rainbow, 03 = Rainbow F, 04 = Candle Effect
speed | 00-> ff, 00 => really slow, 01 => really fast, 02 => slower

#####Candle effect
`saturation + color = ff000000`


0x0017: Get / Set Color
---------------------
Value  | Result
------------- | -------------
00000000 | led off
ff000000 | candle color
00+hex  | hex color

#####Example
00ff0000 => full red

==== Color

0x0016: Effects
---------------
Value: [white][color][mode][00][speed]

Parameter | Value
--------- | -------------
white     | 00 => off, ff => white, 01 -> ff => saturation of white
color     | color as RGB hex
mode      | 00 = Flash, 01 = Pulse, 02 = Rainbow Jump, 03 = Rainbow Fade
not used  | 00
speed     | 46 46 -> 01 01 => Slow to Fast (Flash, Rainbow), 1e 1e -> 01 01 => Slow to Fast (Pulse)

#####Example response
00 ff 00 00 01 00 0f 0f

**Examples** to use with `gatttool -I`
- Off: `char-write-cmd 0x0016 0000000000000000`
- Red pulse effect: `char-write-cmd 0x0016 00ff000001000f0f`
- Green flash effect: `char-write-cmd 0x0016 0000ff0000000f0f`
- White pulse effect: `char-write-cmd 0x0016 ff00000001000f0f`
- Rainbow jump effect: `char-write-cmd 0x0016 00ff000002000f0f`


0x0018: Get / Set Color
-----------------------
Value: [white][color]

Parameter | Value
--------- | -------------
white     | 00 => off, ff => white, 01 -> ff => saturation of white
color     | color as RGB hex

#####Example response
00 ff 00 ff

**Examples** to use with `gatttool -I`
- Off: `char-write-cmd 0x0018 00000000`
- Full white: `char-write-cmd 0x0018 ff000000`
- Full red: `char-write-cmd 0x0018 00ff0000`
- Full green: `char-write-cmd 0x0018 0000ff00`
- Full blue: `char-write-cmd 0x0018 000000ff`

==== Rainbow

0x0016: Effects
---------------------
Value: [white][color][mode][00][speed]

Parameter  | Value
------------- | -------------
white | 00 => off, ff => white, 01-> ff => saturation of white
color | color as RGB hex
mode  | 00 = Flash, 01 = Pulse, 02 = Rainbow Jump, 03 = Rainbow Fade
speed | 46 46-> 01 01 => Slow to Fast (Flash, Rainbow), 1e 1e-> 01 01 => Slow to Fast (Pulse)

#####Red pulse effect
00ff000001000f0f


0x0018: Get / Set Color
---------------------
Value: [white][color]

Parameter  | Value
------------- | -------------
white | 00 => off, ff => white, 01-> ff => saturation of white
color | color as RGB hex

#####Example
00ff0000 => full red
ff000000 => white

==== Garden / Blue Label / Sphere

Comme la Color sauf les commandes :

0x0016 -> 0x0019

0x0018 -> 0x001b

==== Original (sans couleurs)
0x0010: Level
---------------------
Value: 01[level]

Parameter  | Value
------------- | -------------
level | 00 -> off, 14 -> max ( + 13 niveaux intermediaires)

#####Example
0100 => off
0114 => on level max

==== Commandes Utiles

sudo hciconfig

sudo hciconfig hci0 up

sudo hcitool lescan

gatttool -b AC:E6:4B:06:2C:55 --char-write -a 0x0016 -n 0000ff00


==== Source

https://github.com/Phhere/Playbulb
